
version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1111:1111/tcp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
